# Generated by Django 4.2.5 on 2023-09-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_breed_remove_dog_first_name_dog_age_dog_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='language',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='style',
        ),
    ]
